### ISSUE TITLE
Change the implementation of how image list is gathered to use labels

### ISSUE THREAD

**Issue by vpavlin** [vpavlin/jupyterhub-singleuser-profiles#16]
cc @mroman-redhat 

Do this after #15 

Currently the list of images is generated by getting all `ImageStreams` from the namespaces and filtering by their name - looking for suffix `-notebook`.

To follow the best practices, we should use `labels` (`metadata.labels`) to find the `ImageStream`s which we want to list.

If the `ImageStream` has a label `opendatahub.io/notebook-image: true`, it should be added to the list, ignored otherwise

FYI @erikerlandson

**Comment by erikerlandson** [comment]
Looking forward to this one!

I just noticed that the spawner at Honda appears to be pulling in some imagestreams that have 'notebook' in the name, not just '*-notebook' - they aren't even relevant jupyter images.
